version: "3"
services:
  javascripts:
    image: nycdavid/postapoc-js:0.0.1
    volumes:
      - js_volume:/app/dist
      - ./docker.javascripts.src/src:/app/src
  stylesheets:
    image: nycdavid/postapoc-css:0.0.1
    volumes:
      - css_volume:/app/dist
      - ./docker.stylesheets.src/src:/app/src
  postapoc:
    image: nycdavid/postapoc:0.0.1
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - js_volume:/go/src/app/dist/javascripts
      - css_volume:/go/src/app/dist/stylesheets
      - ./static:/go/src/app/dist/static
      - ./main.go:/go/src/app/main.go
    depends_on:
      - javascripts
      - stylesheets
      - postgres
  nightwatch:
    image: nycdavid/nightwatch:0.0.1
    volumes:
      - ./docker.nightwatch.src/tests:/app/tests
      - ./docker.nightwatch.src/videos:/app/videos
    depends_on:
      - chromedriver
      - postapoc
  chromedriver:
    image: nycdavid/chromedriver:0.0.1
    environment:
      - VNC_ENABLED=true
      - EXPOSE_X11=true
    ports:
      - 5900:5900
  postgres:
    image: postgres:10.3-alpine

volumes:
  js_volume:
  css_volume:
