version: "3"
services:
  javascripts:
    image: nycdavid/postapoc-js:0.0.1
    volumes:
      - js_volume:/app/dist/javascripts
      - ./src:/app/src
  stylesheets:
    image: nycdavid/postapoc-css:0.0.1
    volumes:
      - css_volume:/app/dist
      - ./src/stylesheets:/app/src
  postapoc:
    image: nycdavid/postapoc:0.0.1
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - js_volume:/go/src/app/dist/javascripts
      - css_volume:/go/src/app/dist/stylesheets
volumes:
  js_volume:
  css_volume:
