version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/velvetreactor/postapocalypse
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Postapocalypse image
          command: make image-postapoc
      - run:
          name: Build Postapocalypse JS image
          command: make image-js
      - run:
          name: Run Go unit tests
          command: |
            docker-compose \
            -f docker-compose.circleci.yml \
            run \
            postapoc \
            go test -v ./...
      - run:
          name: Run Javascript unit tests
          command: |
            docker run \
            nycdavid/postapoc-js:0.0.1 \
            npm t
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
