version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
      - image: postgres:10.3-alpine
    working_directory: /go/src/github.com/velvetreactor/postapocalypse
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create Postapoc network
          command: docker network create postapoc
      - run:
          name: Start Postgres
          command: docker run --network postapoc --name postgres -d -p 5432:5432 postgres:10.3-alpine
      - run:
          name: Run Go unit tests
          command: |
            docker run \
            --network postapoc \
            -e PORT=3000 \
            -e PGCONN=postgres://postgres@postgres/postgres?sslmode=disable \
            -e SESSION_SECRET=developmentsecretxyz \
            nycdavid/postapoc:0.0.1 \
            go test -v ./...
      - run:
          name: Run Javascript unit tests
          command: |
            docker run \
            --network postapoc \
            nycdavid/postapoc-js:0.0.1 \
            npm t
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
